spark.master                             spark://spark-master:7077
spark.eventLog.enabled                   true
spark.eventLog.dir                       file:///tmp/spark-events
spark.sql.warehouse.dir                  /tmp/spark-warehouse
spark.hadoop.fs.defaultFS                hdfs://namenode:9000
spark.hadoop.hive.metastore.uris         thrift://hive-metastore:9083
spark.sql.catalogImplementation          hive
spark.driver.memory                      1g
spark.executor.memory                    1g
spark.executor.cores                     1
spark.sql.adaptive.enabled               true
spark.sql.shuffle.partitions             8
spark.serializer                         org.apache.spark.serializer.KryoSerializer
